export const PrinterErrors = {
    USER_CREDENTIAL_REQUIRED: 'USER_CREDENTIAL_REQUIRED',
    NO_OWNED_PRINTER: 'NO_OWNED_PRINTER',
    NO_ONLINE_PRINTER: 'NO_ONLINE_PRINTER',
}

export const PageErrors = {
    NOT_FOUND: 'NOT_FOUND'
}